# Generated by Django 6.0.4 on 2026-04-11 07:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('plate', models.CharField(max_length=10, unique=True)),
                ('vehicle_type', models.CharField(choices=[('truck', 'Truck'), ('personal_car', 'Personal Car'), ('taxi', 'Taxi'), ('coaster', 'Coaster'), ('boda_boda', 'Boda-boda')], max_length=20)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('nin', models.CharField(blank=True, max_length=20)),
                ('arrival_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('parked', 'Parked'), ('signed_out', 'Signed Out')], default='parked', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=20, unique=True)),
                ('receiver_name', models.CharField(max_length=200)),
                ('receiver_phone', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('nin', models.CharField(blank=True, max_length=20)),
                ('sign_out_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('fee', models.IntegerField(default=0)),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parking.vehicle')),
            ],
        ),
    ]
