# Generated by Django 6.0.4 on 2026-04-19 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_alter_parkingtransaction_sign_out_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingtransaction',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='parking.vehicle'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate',
            field=models.CharField(max_length=10),
        ),
    ]
