# Generated by Django 6.0.4 on 2026-04-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batterytransaction',
            name='hire_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
