# Generated by Django 6.0.4 on 2026-04-11 08:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TyreService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=10)),
                ('driver_name', models.CharField(max_length=200)),
                ('service_type', models.CharField(choices=[('pressure', 'Pressure Check'), ('puncture', 'Puncture Fixing'), ('valve', 'Valve Replacement'), ('tyre_13', 'Tyre Size 13'), ('tyre_14', 'Tyre Size 14'), ('tyre_15', 'Tyre Size 15'), ('tyre_16', 'Tyre Size 16')], max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
